# Generated by Django 5.2 on 2025-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlist_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='movie_name',
            field=models.CharField(default='unkown', max_length=250),
            preserve_default=False,
        ),
    ]
